# R for travis:      see documentation at https://docs.travis-ci.com/user/languages/r

language:            R
sudo:                false
cache:               packages
warnings_are_errors: false
r:
  - 3.4.1
  - oldrel
  - release
  - devel
notifications:
     slack:          kaspectscientists:OFGveqm4qxt26CPytZrHUxSV
after_success:
      - Rscript -e 'library(covr); codecov()'
      - bash <(curl -s https://codecov.io/bash)
      - Rscript -e 'lintr::lint_package(".", linters = lintr::with_defaults(lintr::line_length_linter(120)))'
before_install:
    - Rscript -e 'update.packages(ask = FALSE)'
